"use client";

import Image from "next/image";
import type { ReportJson } from "@/lib/types";
import { assetUrl } from "@/lib/paths";
import {
  buildQualityProfile,
  buildReportKpi,
  buildPriorityImprovements,
} from "@/lib/qualityProfile";
import { buildPdfContext, pageAxeCount } from "@/lib/reportPdfData";
import { pdfExecutiveLine } from "@/lib/reportCopy";
import { shareStatusLabelEn } from "@/lib/reportCopy";
import { RadarChart } from "@/components/RadarChart";
import { ScoreTierBadge, StatusBadge } from "@/components/ReportCharts";
import {
  ReportIcon,
  Clock,
  FileText,
  Layers,
  AlertTriangle,
  Timer,
} from "@/lib/reportIcons";

type Props = {
  report: ReportJson;
};

export function ReportPdfDocument({ report }: Props) {
  const { summary, targetUrl, completedAt, pages, timing, crawlMeta } = report;
  const axes = buildQualityProfile(report);
  const priorities = buildPriorityImprovements(axes);
  const kpi = buildReportKpi(report);
  const { issues, seoChecklist } = buildPdfContext(report);
  const bd = summary.healthBreakdown;
  const profile = report.deviceProfile || crawlMeta?.deviceProfile;
  const applied = report.crawlLimits?.applied;

  const dateShort = completedAt
    ? new Date(completedAt).toLocaleDateString("ko-KR", {
        year: "numeric",
        month: "2-digit",
        day: "2-digit",
      })
    : "—";
  const statusEn = shareStatusLabelEn(summary.statusLabel);

  return (
    <article className="pdf-doc text-[#0f172a]">
      <section className="pdf-sheet pdf-cover">
        <Image
          src={assetUrl("/favicon.png")}
          alt=""
          width={120}
          height={120}
          className="pdf-cover-watermark"
          unoptimized
        />
        <div className="pdf-cover-body">
          <Image
            src={assetUrl("/favicon.png")}
            alt=""
            width={56}
            height={56}
            className="pdf-cover-favicon"
            unoptimized
          />
          <p className="pdf-eyebrow">SCOPURL</p>
          <h1 className="pdf-cover-title">Website Quality Report</h1>
          <p className="pdf-cover-url">{targetUrl}</p>
          <div className="pdf-cover-score-row">
            <span className="pdf-cover-score">{summary.healthScore}</span>
            <span className="pdf-cover-badge">{statusEn}</span>
            {summary.statusLabel && (
              <StatusBadge status={summary.statusLabel} />
            )}
          </div>
          <p className="pdf-cover-meta">{dateShort}</p>
          <p className="pdf-cover-footer">Generated by SCOPURL</p>
        </div>
      </section>

      <section className="pdf-sheet">
        <h2 className="pdf-h2">
          <ReportIcon icon={FileText} size={18} className="pdf-h2-icon" />
          Executive Summary
        </h2>
        <p className="pdf-lead">{pdfExecutiveLine(summary.statusLabel)}</p>

        {priorities.length > 0 && (
          <>
            <h3 className="pdf-h3">우선 개선 TOP3</h3>
            <div className="pdf-priority-row">
              {priorities.map((p, i) => (
                <div key={p.axis.key} className="pdf-priority-card pdf-avoid-break">
                  <span className="pdf-rank">{i + 1}</span>
                  <p className="font-semibold">{p.axis.label}</p>
                  <p className="text-xl font-bold">{p.axis.score}점</p>
                  <p className="text-[10px] leading-snug text-[#64748b]">
                    {p.problemSummary}
                  </p>
                  <p className="pdf-gain">+{p.expectedGain}점</p>
                </div>
              ))}
            </div>
          </>
        )}

        <div className="pdf-exec-grid">
          <div className="pdf-radar-wrap">
            <RadarChart axes={axes} size={200} />
          </div>
          <div className="pdf-kpi-col">
            <PdfKpi icon={Layers} label="분석 페이지" value={`${kpi.pageCount}개`} />
            <PdfKpi
              icon={AlertTriangle}
              label="발견 이슈"
              value={`${kpi.issueCount}건`}
            />
            <PdfKpi
              icon={Timer}
              label="분석 시간"
              value={
                kpi.analysisSeconds != null
                  ? `${Math.round(kpi.analysisSeconds)}초`
                  : "—"
              }
            />
          </div>
        </div>

        <h2 className="pdf-h2 pdf-h2-spaced">품질 프로필 상세</h2>
        <div className="pdf-axis-list">
          {axes.map((axis) => (
            <div key={axis.key} className="pdf-axis-row pdf-avoid-break">
              <p className="font-semibold">{axis.label}</p>
              <p className="text-[10px] text-[#64748b]">{axis.cardDescription}</p>
              <div className="text-right">
                <p className="text-lg font-bold">{axis.score}</p>
                <ScoreTierBadge tier={axis.tier} label={axis.tierLabel} />
              </div>
            </div>
          ))}
        </div>

        {bd && (
          <>
            <h2 className="pdf-h2 pdf-h2-spaced">점수 산정 근거</h2>
            <div className="pdf-breakdown">
              {bd.contributions.map((c) => (
                <div key={c.category} className="pdf-breakdown-row">
                  <span>{c.label}</span>
                  <div className="pdf-breakdown-bar-track">
                    <div
                      className="pdf-breakdown-bar-fill"
                      style={{
                        width: `${Math.min(100, (c.weightedPoints / 30) * 100)}%`,
                      }}
                    />
                  </div>
                  <span>+{c.weightedPoints}</span>
                </div>
              ))}
              {bd.penaltyTotal > 0 && (
                <div className="pdf-breakdown-row">
                  <span>감점</span>
                  <div className="pdf-breakdown-bar-track">
                    <div className="pdf-breakdown-bar-fill pdf-breakdown-penalty" />
                  </div>
                  <span>−{bd.penaltyTotal}</span>
                </div>
              )}
              <div className="pdf-breakdown-final">
                <span>최종</span>
                <strong>{summary.healthScore}</strong>
              </div>
            </div>
          </>
        )}
      </section>

      <section className="pdf-sheet">
        {priorities.length > 0 && (
          <>
            <h2 className="pdf-h2">우선 개선 권장 사항</h2>
            {priorities.map((p) => (
              <div key={p.axis.key} className="pdf-rec-block pdf-avoid-break">
                <h3 className="pdf-h3">{p.axis.label}</h3>
                <p className="text-sm">
                  <strong>문제</strong> — {p.problemSummary}
                </p>
                <p className="text-sm">
                  <strong>권장</strong> — {p.actions.join(" · ")}
                </p>
                <p className="pdf-gain">예상 +{p.expectedGain}점</p>
              </div>
            ))}
          </>
        )}

        {issues.length > 0 && (
          <>
            <h2 className="pdf-h2 pdf-h2-spaced">발견된 이슈 상세</h2>
            {issues.slice(0, 10).map((issue) => (
              <div key={issue.id} className="pdf-issue-card pdf-avoid-break">
                <p className={`pdf-severity pdf-severity-${issue.severity}`}>
                  {issue.severity.toUpperCase()}
                </p>
                <p className="font-semibold text-sm">{issue.title}</p>
                <p className="text-[10px] text-[#64748b]">{issue.location}</p>
                <p className="pdf-rec-box text-[10px]">{issue.recommendation}</p>
              </div>
            ))}
          </>
        )}
      </section>

      <section className="pdf-sheet">
        <h2 className="pdf-h2">페이지별 진단</h2>
        <table className="pdf-table">
          <thead>
            <tr>
              <th>URL</th>
              <th>상태</th>
              <th>성능</th>
              <th>접근성</th>
              <th>SEO</th>
              <th>이슈</th>
            </tr>
          </thead>
          <tbody>
            {pages.map((p) => {
              const issueN =
                pageAxeCount(p) +
                (p.uiIssues?.filter((i) => i.severity !== "info").length ?? 0);
              return (
                <tr key={p.url}>
                  <td className="max-w-[160px] text-[9px]">{p.url}</td>
                  <td>{p.statusCode ?? "—"}</td>
                  <td>{p.lighthouse?.performance ?? "—"}</td>
                  <td>{pageAxeCount(p)}</td>
                  <td>{p.lighthouse?.seo ?? "—"}</td>
                  <td>{issueN}</td>
                </tr>
              );
            })}
          </tbody>
        </table>

        <h2 className="pdf-h2 pdf-h2-spaced">SEO 분석</h2>
        <ul className="pdf-seo-checklist">
          {seoChecklist.map((item) => (
            <li key={item.id} className="pdf-seo-item pdf-avoid-break">
              <span className={`pdf-seo-status pdf-seo-${item.status}`}>
                {seoStatusLabel(item.status)}
              </span>
              <div>
                <p className="font-semibold text-sm">{item.label}</p>
                <p className="text-[10px] text-[#64748b]">{item.note}</p>
              </div>
            </li>
          ))}
        </ul>

        <h2 className="pdf-h2 pdf-h2-spaced">분석 범위</h2>
        <dl className="pdf-dl">
          <PdfDl label="분석 페이지" value={`${kpi.pageCount}개`} />
          <PdfDl label="발견 링크" value={`${kpi.linkCount}개`} />
          <PdfDl
            label="크롤 깊이"
            value={applied?.maxDepth != null ? String(applied.maxDepth) : "—"}
          />
          <PdfDl
            label="최대 페이지"
            value={applied?.maxPages != null ? String(applied.maxPages) : "—"}
          />
          <PdfDl
            label="분석 환경"
            value={
              profile === "mobile"
                ? "모바일 (390px)"
                : profile === "desktop"
                  ? "데스크톱 (1440px)"
                  : "—"
            }
          />
          {timing?.totalSeconds != null && (
            <PdfDl
              label="실행 시간"
              value={`${Math.round(timing.totalSeconds)}초`}
            />
          )}
        </dl>
        <p className="pdf-footer-note">
          <ReportIcon icon={Clock} size={12} /> Generated by SCOPURL · {dateShort}
        </p>
      </section>
    </article>
  );
}

function PdfKpi({
  icon: Icon,
  label,
  value,
}: {
  icon: typeof Layers;
  label: string;
  value: string;
}) {
  return (
    <div className="pdf-kpi">
      <ReportIcon icon={Icon} size={14} className="text-[#00a66a]" />
      <div>
        <p className="text-[10px] text-[#64748b]">{label}</p>
        <p className="font-bold">{value}</p>
      </div>
    </div>
  );
}

function PdfDl({ label, value }: { label: string; value: string }) {
  return (
    <>
      <dt>{label}</dt>
      <dd>{value}</dd>
    </>
  );
}

function seoStatusLabel(s: string) {
  if (s === "pass") return "충족";
  if (s === "warn") return "개선 권장";
  if (s === "fail") return "누락";
  return "확인 필요";
}
