function esc(s) {
  return String(s)
    .replaceAll("&", "&amp;")
    .replaceAll("<", "&lt;")
    .replaceAll(">", "&gt;")
    .replaceAll('"', "&quot;")
    .replaceAll("'", "&#039;");
}

export function renderReportHtml(report) {
  const { summary, pages, quick, targetUrl, reportId } = report;
  const rows = pages
    .map(
      (p) => `
      <tr>
        <td class="mono"><a href="${esc(p.url)}">${esc(p.url)}</a></td>
        <td>${p.statusCode ?? "—"}</td>
        <td>${p.lighthouse?.performance ?? "—"}</td>
        <td>${(p.axeViolations || []).reduce((s, v) => s + v.nodes, 0)}</td>
        <td>${p.consoleErrors?.length ?? 0}</td>
        <td>${p.failedRequests?.length ?? 0}</td>
      </tr>`,
    )
    .join("");

  const shots = pages
    .map((p) => {
      const mobile = p.screenshotPaths?.mobile
        ? `<img class="shot" src="${esc(p.screenshotPaths.mobile)}" alt="mobile" />`
        : "";
      return `<section class="card"><h3 class="mono">${esc(p.url)}</h3><div class="shots">${mobile}</div></section>`;
    })
    .join("");

  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <title>SiteScope report ${esc(reportId)}</title>
  <style>
    :root { color-scheme: dark; }
    body { margin:0; font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial; background:#0b1220; color:#e5e7eb; }
    .wrap { max-width:1100px; margin:0 auto; padding:28px 18px 60px; }
    h1 { font-size:28px; margin:0 0 8px; }
    .sub { color:#94a3b8; margin-bottom:22px; }
    .grid { display:grid; grid-template-columns: repeat(auto-fit, minmax(180px,1fr)); gap:12px; margin: 18px 0 26px; }
    .tile { background:#111827; border:1px solid #1f2937; border-radius:12px; padding:14px; }
    .tile p { margin:0; color:#94a3b8; font-size:12px; text-transform:uppercase; letter-spacing:.08em; }
    .tile strong { display:block; margin-top:8px; font-size:26px; }
    table { width:100%; border-collapse:collapse; background:#0f172a; border-radius:12px; overflow:hidden; border:1px solid #1f2937; }
    th, td { text-align:left; padding:10px 12px; border-bottom:1px solid #1f2937; font-size:13px; vertical-align:top; }
    th { background:#111827; color:#cbd5e1; font-weight:600; }
    .mono { word-break: break-all; font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace; font-size:12px;}
    .card { margin-top:16px; padding:14px; border:1px solid #1f2937; border-radius:12px; background:#0f172a; }
    .shots { display:flex; gap:10px; flex-wrap:wrap; margin-top:10px; }
    .shot { max-width: 360px; width:100%; border-radius:10px; border:1px solid #1f2937; }
    a { color:#60a5fa; }
  </style>
</head>
<body>
  <div class="wrap">
    <h1>SiteScope report</h1>
    <p class="sub">Target: <span class="mono">${esc(targetUrl)}</span> · ID: <span class="mono">${esc(
      reportId,
    )}</span></p>
    <div class="grid">
      <div class="tile"><p>종합 건강 점수</p><strong>${summary.healthScore}</strong></div>
      <div class="tile"><p>성능</p><strong>${
        summary.avgLighthousePerformance ?? "—"
      }</strong></div>
      <div class="tile"><p>Avg accessibility issues (nodes / page)</p><strong>${
        summary.avgAxeIssuesPerPage
      }</strong></div>
      <div class="tile"><p>스크립트 오류</p><strong>${
        summary.totalConsoleErrors
      }</strong></div>
    </div>

    <h2>Quick signals</h2>
    <div class="card mono" style="white-space:pre-wrap">${esc(
      JSON.stringify(quick, null, 2),
    )}</div>

    ${
      summary.mobileWarnings?.length
        ? `<h2>Responsiveness warnings</h2><ul>${summary.mobileWarnings
            .map((w) => `<li>${esc(w)}</li>`)
            .join("")}</ul>`
        : ""
    }

    <h2>Per-page overview</h2>
    <table>
      <thead><tr><th>URL</th><th>Status</th><th>LH perf</th><th>Axe nodes</th><th>Console</th><th>Failed net</th></tr></thead>
      <tbody>${rows}</tbody>
    </table>

    <h2>Screenshots (mobile)</h2>
    ${shots}

    <p class="sub" style="margin-top:26px">Generated by SiteScope · ${esc(
      report.completedAt || "",
    )}</p>
  </div>
</body>
</html>`;
}
